name: BuildTestAndCreateDist
on: 
  push:
      branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true
jobs:
    build:
        uses: eed-web-application/aosd-shift-reporting-backend-deployment/.github/workflows/build-test-create.yml@main
        secrets: inherit

